export * from './getUserResponse.interface';
export * from './tokens.interface';
export * from './specialistTypesResponse.interface';
export * from './specialist.interface';
export * from './user.interface';
export * from './getResponse.interface';
export * from './person.interface';
export * from './representative.interface';
export * from './patient.interface';
